server:
  port: 8762

spring:
  application:
    name: eureka-client1

# 注册时需要知道server的地址eureka.client.service-url.defaultZone
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/